name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install and Build
        run: |
          npm install
          npm install hexo-cli -g
          hexo generate

      - name: Deploy to server
        run: |
          rsync -avz --delete public/ root@137.175.53.140:/var/www/html
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
